sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

before_install:
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src tests